api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from api.views import CreateUserView, UserView, SelfUserProfileView

urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("register/", CreateUserView.as_view(), name="create_profile"),
    path(
        "profile/all/", UserView.as_view({"get": "list"}), name="all_profile"
    ),
    path("profile/me/", SelfUserProfileView.as_view(), name="my_profile"),
]

app_name = "api"

catalog/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from catalog.views import (
    index,
    LoginView,
    # SignUpView,
    TaskListView,
    TaskDetailView,
    TaskStatusUpdateView,
    TaskCreateView,
    TaskDeleteView,
    ProfileView,
    activate,
    signup,
)

urlpatterns = [
    path("", index, name="index"),
    path("registrate/", signup, name="registrate"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="catalog:index"), name="logout"),
    path("task/", TaskListView.as_view(), name="task_url_list"),
    path("task/create/", TaskCreateView.as_view(), name="task_url_create"),
    path(
        "task/<int:pk>/update_status/",
        TaskStatusUpdateView.as_view(),
        name="update_task_status",
    ),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_url_detail"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_url_delete"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile_url_detail"),
    path("emailVerification/<uidb64>/<token>", activate, name="emailActivate"),
]

app_name = "catalog"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views

handler404 = views.page_not_found
handler403 = views.permission_denied
handler500 = views.server_error

urlpatterns = [
    path("", include("catalog.urls", namespace="catalog")),
    path("admin/", admin.site.urls),
    path("auth/", include("social_django.urls", namespace="social")),
    path("api/", include("api.urls", namespace="api")),
    path("api/", include("rest_framework.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block title %} Sign IN {% endblock %}

{% block body_class %} sign-in-basic {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    <style>
    .form-control {
      mask: 1px;
      box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
      border-radius: 10px;
      padding: 8px;
    }


  </style>
{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation-transparent.html' %}

  <div class="page-header align-items-start min-vh-100 animate__animated animate__fadeIn" style="background-image: url('{{ ASSETS_ROOT }}/img/bg_forest.jpeg')" loading="lazy">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container my-auto" style="min-width: 350px">
      <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
          <div class="card z-index-0 fadeIn3 animate__animated animate__fadeIn fadeInBottom">
            <a href="{% url 'catalog:index' %}">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-dark shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">
                    Task Manager
                  </h4>
                  <div class="row mt-3">
                    <p class="mb-0 text-white text-center">
                      {% if msg %}
                        {{ msg | safe }}
                      {% else %}
                        Enter your credentials
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
            </a>
          <div class="card-body">
            <div class="card-body">
                <form role="form" method="POST" class="mx-auto m-lg-1">
                  {% csrf_token %}
                  {{ form|crispy}}
                  <div class="form-group text-center">
                    <button class="w-25 mt-2 btn btn-sm btn-dark bg-gradient-dark" type="submit" style="min-width: 80px">Sign IN</button>
                  </div>
                </form>

            </div>
            <div class="form-check form-switch d-flex align-items-center mb-3">
              <input class="form-check-input" type="checkbox" id="rememberMe">
              <label class="form-check-label mb-0 ms-2" for="rememberMe">Remember me</label>
            </div>
            <p class="mt-4 text-sm text-center">
              Don't have an account?
              <a href="{% url 'catalog:registrate' %}" class="text-dark text-gradient font-weight-bold">Sign UP</a>
            <div style="display: flex; justify-content: center; align-items: center;">
                <div class="mt-2 btn btn-sm btn-round">
                  <a class="w-40" href="{% url 'social:begin' 'google-oauth2' %}">
                    Login with
                    <img class="w-25" src="{{ ASSETS_ROOT }}/img/google.svg" alt="Google Logo">
                  </a>
                </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>

    {% include 'includes/footer-auth.html' %}

  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% load crispy_forms_tags %}

{% block title %} Sign UP {% endblock %}

{% block body_class %} sign-in-basic {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    <style>
    .form-control {
      mask: 1px;
      box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
      border-radius: 10px;
      padding: 8px;
    }


  </style>
{% endblock stylesheets %}

{% block content %}

{% include 'includes/navigation-transparent.html' %}

  <div class="page-header align-items-start min-vh-100 animate__animated animate__fadeIn" style="background-image: url('{{ ASSETS_ROOT }}/img/bg_registratre.jpeg');" loading="lazy">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
          <div class="card mt-5 animate__animated animate__backInLeft animate__fast z-index-0 fadeIn3 fadeInBottom" style="min-width: 350px">
            <a href="{% url 'catalog:index' %}">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-dark shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">
                    Task Manager
                  </h4>
                  <div class="row mt-3">
                    <p class="mb-0 text-white text-center">
                      {% if msg %}
                        {{ msg | safe }}
                      {% else %}
                        Enter your login and password to register
                      {% endif %}
                    </p>
                  </div>
                </div>
              </div>
             </a>
            <div class="card-body">
            {% if not success %}
            <form class="" role="form" method="post" action="">
              {% csrf_token %}
              {{ form|crispy}}
              <div class="text-center">
                <button type="submit" name="register" class="btn btn-lg bg-gradient-dark btn-lg w-100 mt-4 mb-0">Sign Up</button>
              </div>
              <p class="mt-4 text-sm text-center">
                Already have an account?
                <a href="{% url 'catalog:login' %}" class="text-dark text-gradient font-weight-bold">Sign IN</a>
              </p>

            </form>

            <div style="display: flex; justify-content: center; align-items: center;">
                <div class="mt-2 btn btn-sm btn-round">
                  <a class="w-40" href="{% url 'social:begin' 'google-oauth2' %}">
                    Login with
                    <img class="w-25" src="{{ ASSETS_ROOT }}/img/google.svg" alt="Google Logo">
                  </a>
                </div>
            </div>
          {% else %}

            <p class="mt-4 text-sm text-center">
              <a href="{% url 'catalog:login' %}" class="text-dark text-gradient font-weight-bold">Sign IN</a>
            </p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'includes/footer-auth.html' %}
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}