api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from api.views import CreateUserView, UserView, SelfUserProfileView

urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("register/", CreateUserView.as_view(), name="create_profile"),
    path(
        "profile/all/", UserView.as_view({"get": "list"}), name="all_profile"
    ),
    path("profile/me/", SelfUserProfileView.as_view(), name="my_profile"),
]

app_name = "api"

catalog/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from catalog.views import (
    index,
    LoginView,
    # SignUpView,
    TaskListView,
    TaskDetailView,
    TaskStatusUpdateView,
    TaskCreateView,
    TaskDeleteView,
    ProfileView,
    activate,
    signup,
)

urlpatterns = [
    path("", index, name="index"),
    path("registrate/", signup, name="registrate"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="catalog:index"), name="logout"),
    path("task/", TaskListView.as_view(), name="task_url_list"),
    path("task/create/", TaskCreateView.as_view(), name="task_url_create"),
    path(
        "task/<int:pk>/update_status/",
        TaskStatusUpdateView.as_view(),
        name="update_task_status",
    ),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_url_detail"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_url_delete"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile_url_detail"),
    path("emailVerification/<uidb64>/<token>", activate, name="emailActivate"),
]

app_name = "catalog"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views

handler404 = views.page_not_found
handler403 = views.permission_denied
handler500 = views.server_error

urlpatterns = [
    path("", include("catalog.urls", namespace="catalog")),
    path("admin/", admin.site.urls),
    path("auth/", include("social_django.urls", namespace="social")),
    path("api/", include("api.urls", namespace="api")),
    path("api/", include("rest_framework.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
      <div class="container">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-12 col-md-6 my-auto">
            <div class="copyright text-center text-sm text-white text-lg-start">
              &copy; <a href="https://github.com/Soobig666" class="font-weight-bold text-white" target="_blank"> - Coded By Soobig666.</a>
            </div>
          </div>
          <div class="col-12 col-md-6">
          </div>
        </div>
      </div>
</footer>

templates/includes/footer-components.html
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Company
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            About Us
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Team
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Products
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Blog
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Pricing
          </a>
        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-dribbble"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-twitter"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-instagram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-pinterest"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            &copy; <a href="https://github.com/Soobig666" class="font-weight-bold" target="_blank"></a>
              coded by Soobig666
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <a href="https://github.com/Soobig666">
              <img src="{{ ASSETS_ROOT }}/img/logo-6-1.png" class="mb-3 footer-logo" alt="main_logo">
            </a>
          </div>
          <div>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/Soobig666" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://github.com/Soobig666" target="_blank">
                  About Me
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">

        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="text-dark my-4 text-sm font-weight-normal">
              &copy; <a href="https://github.com/Soobig666" target="_blank"></a> - Coded By Soobig666.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation-transparent.html
  <!-- Navbar Transparent -->
  <nav class=" navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3  navbar-transparent ">
    <div class="container ">
      <a class="w-13 mt-2 btn btn-sm btn-dark bg-gradient-dark" type="button" href="{% url 'catalog:index' %}" rel="tooltip" title="Home page" data-placement="bottom">
        Home
      </a>
          {% if request.user.is_authenticated %}
            <li class="nav-item ms-lg-auto">
              <a class="nav-link nav-link-icon me-2"
                href="{% url 'catalog:logout' %}">
                <i class="fa fa-sign-out me-1"></i>
                <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
              </a>
            </li>
          {% endif %}
    </div>
  </nav>

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg blur border-radius-xl mt-4 top-0 z-index-3 shadow-primary position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0" style="justify-content: right;">
          <ul class="navbar-nav navbar-nav-hover pb-2 py-lg-0 w-100">

          </ul>
        <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-25" id="navigation">
          <ul class="navbar-nav navbar-nav-hover ms-auto">
          </ul>
        </div>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation" style="min-width:150px">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item">
              <a href="https://github.com/Soobig666/it-company-task-manager/"  type="button" class="btn btn-sm btn-outline-secondary bg-gradient-dark mb-0 me-1 mt-2 mt-md-0">GitHub</a>
              </li>
              <li>
                <a class="dropdown-item border-radius-md" href="{% url 'catalog:index' %}" rel="tooltip" title="Home page" data-placement="bottom">
                  Home
                </a>
              </li>
              <li>
                <a class="dropdown-item border-radius-md" href="{% url 'catalog:task_url_list' %}" rel="tooltip" data-placement="bottom">
                Tasks
                </a>
              </li>
                {% if request.user.is_authenticated %}
                  <div class=" nav-item ms-lg-auto ">
                    <a class="nav-link nav-link-icon me-2"
                      href="{{ user.get_absolute_url }}">
                      <p class="d-inline text-sm z-index-1 font-weight-bold"  data-bs-toggle="tooltip" data-bs-placement="bottom" title="Profile">{{ user.get_username }}</p>
                    </a>
                  </div>
                    <div class="shadow-dark rounded-3 nav-item ms-lg-auto" >
                      <a class="nav-link nav-link-icon"
                        href="{% url 'catalog:logout' %}?next={{ request.path }}">
                        <i class="fa rounded-3 fa-sign-out"></i>
                        <p class="d-inline  text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT"></p>
                      </a>
                    </div>
                {% else %}
                  <div class="rounded-3">
                    <a href="{% url 'catalog:login' %}?next={{ request.path }}" class="shadow-dark dropdown-item border-radius-md">
                      <span>Sign In</span>
                    </a>
                  </div>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>