api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from api.views import CreateUserView, UserView, SelfUserProfileView

urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("register/", CreateUserView.as_view(), name="create_profile"),
    path(
        "profile/all/", UserView.as_view({"get": "list"}), name="all_profile"
    ),
    path("profile/me/", SelfUserProfileView.as_view(), name="my_profile"),
]

app_name = "api"

catalog/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from catalog.views import (
    index,
    LoginView,
    # SignUpView,
    TaskListView,
    TaskDetailView,
    TaskStatusUpdateView,
    TaskCreateView,
    TaskDeleteView,
    ProfileView,
    activate,
    signup,
)

urlpatterns = [
    path("", index, name="index"),
    path("registrate/", signup, name="registrate"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="catalog:index"), name="logout"),
    path("task/", TaskListView.as_view(), name="task_url_list"),
    path("task/create/", TaskCreateView.as_view(), name="task_url_create"),
    path(
        "task/<int:pk>/update_status/",
        TaskStatusUpdateView.as_view(),
        name="update_task_status",
    ),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_url_detail"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_url_delete"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile_url_detail"),
    path("emailVerification/<uidb64>/<token>", activate, name="emailActivate"),
]

app_name = "catalog"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views

handler404 = views.page_not_found
handler403 = views.permission_denied
handler500 = views.server_error

urlpatterns = [
    path("", include("catalog.urls", namespace="catalog")),
    path("admin/", admin.site.urls),
    path("auth/", include("social_django.urls", namespace="social")),
    path("api/", include("api.urls", namespace="api")),
    path("api/", include("rest_framework.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


def get_worker_model():
    from user.models import Worker

    return Worker


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=155, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    STR_CHOICES = [
        ("!!!", "Extra priority"),
        ("!!", "Priority"),
        ("!", "Standard"),
        ("", "No priority"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=True)
    priority = models.CharField(max_length=3, choices=STR_CHOICES)
    task_type = models.ForeignKey(to=TaskType, on_delete=models.DO_NOTHING)
    assignees = models.ManyToManyField(to=get_worker_model(), related_name="assignees")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Tasks"
        ordering = ["-deadline"]

catalog/forms.py
from datetime import date

from django.contrib.auth import forms as auth, authenticate
from django import forms
from django.core.exceptions import ValidationError
from django.forms import DateInput

from .models import Task
from user.models import Worker


class LoginForm(auth.AuthenticationForm):
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        wait_verification = Worker.objects.filter(
            email=username, is_active=False, waiting_verified=True
        )
        try:
            passwords_match = wait_verification.get().check_password(password)
        except Worker.DoesNotExist:
            passwords_match = False
        if username is not None and password:
            self.user_cache = authenticate(
                self.request, username=username, password=password
            )
            if wait_verification and passwords_match:
                raise ValidationError(
                    "This account is inactive. Check your email and activate your account.",
                    code="inactive",
                )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    class Meta:
        model = Worker


class RegistrationForm(auth.UserCreationForm):
    username = forms.CharField(label="Username", required=False)
    first_name = forms.CharField(label="First name", required=False)
    email = forms.EmailField(label="Email", required=True)

    class Meta(auth.UserCreationForm.Meta):
        model = Worker
        fields = auth.UserCreationForm.Meta.fields + (
            "username",
            "email",
            "first_name",
            "last_name",
            "position",
        )
        widgets = {
            "position": forms.RadioSelect(),
        }

    def save(self, commit=True):
        worker = super().save(commit=False)
        if commit:
            worker.save()
            self.save_m2m()
        return worker


class TaskForm(forms.ModelForm):
    deadline = forms.DateField(widget=DateInput(attrs={"type": "date"}))

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "deadline",
            "priority",
            "task_type",
            "assignees",
        ]
        widgets = {
            "assignees": forms.CheckboxSelectMultiple(),
            "priority": forms.RadioSelect(),
            "task_type": forms.RadioSelect(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["priority"].required = False

    def clean_deadline(self):
        deadline = self.cleaned_data.get("deadline")
        if deadline and deadline < date.today():
            raise forms.ValidationError("The date cannot be in the past.")
        return deadline


class ProfileForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        current_user = request.user
        # <-- if current_user.is_superuser then he can edit eny profile -->
        if current_user.is_superuser:
            self.fields["username"].required = True
        # <-- if current_user.is_superuser he can edit only own profile-->
        if not current_user.is_superuser and self.instance.pk != current_user.id:
            self.fields["username"].disabled = True
            self.fields["first_name"].disabled = True
            self.fields["last_name"].disabled = True
            self.fields["email"].disabled = True
            self.fields["date_joined"].disabled = True
            self.fields["position"].disabled = True

    class Meta:
        model = Worker
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "position",
        ]
        widgets = {
            "position": forms.RadioSelect(),
        }

catalog/views.py
import threading

import task_manager.settings

from .forms import (
    LoginForm,
    RegistrationForm,
    TaskForm,
    ProfileForm,
)
from .models import (
    Task,
    TaskType,
    Position,
)
from user.models import Worker
from tokens.account_activation_token import token_manager

from social_django.models import Code
from social_core.exceptions import AuthMissingParameter

from datetime import date
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.db import transaction
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.views import generic
from django.views.decorators.http import require_POST
from django.core.mail import send_mail
from django.template.loader import render_to_string


def index(request):
    num_task = Task.objects.count()
    num_task_solved = Task.objects.filter(is_completed=False).count()
    num_task_actual = Task.objects.filter(is_completed=True).count()
    num_worker = Worker.objects.count()
    num_position = Position.objects.count()
    num_task_type = TaskType.objects.count()

    context = {
        "num_task": num_task,
        "num_worker": num_worker,
        "num_position": num_position,
        "num_task_type": num_task_type,
        "num_task_solved": num_task_solved,
        "num_task_actual": num_task_actual,
    }
    return render(request, "catalog/index.html", context=context)


class LoginView(generic.FormView):
    form_class = LoginForm
    template_name = "accounts/login.html"

    def get_success_url(self):
        return self.request.GET.get("next") or reverse_lazy("catalog:index")

    def form_valid(self, form):
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


def send_mail_in_thread(mail_subject, message, sender, recipient_list):
    """
    Function for sending an email in a separate thread.
    """
    send_mail(mail_subject, message, sender, recipient_list)


def signup(request):
    user_model = get_user_model()
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        form_valid = True if form.is_valid() else False
        if form_valid:
            user = form.save(commit=False)
            if not user.username:
                user.username = user.email.split("@")[0]
            user.is_active = False
            user.waiting_verified = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = "Activate your account."
            message = render_to_string(
                "email/message.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": token_manager.make_token(user),
                },
            )
            to_email = form.cleaned_data.get("email")
            sender = task_manager.settings.EMAIL_HOST_USER
            mail_thread = threading.Thread(
                target=send_mail_in_thread,
                args=(mail_subject, message, sender, [to_email]),
            )
            mail_thread.start()

            return render(request, "email/successful_registrate.html")
    else:
        form = RegistrationForm()
    return render(request, "accounts/register.html", {"form": form})


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and token_manager.check_token(user, token):
        user.is_active = True
        user.waiting_verified = False
        user.save()
        return render(request, "email/activate.html")
    else:
        return render(request, "email/deactivate.html")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "catalog/task_list.html"
    context_object_name = "tasks_view_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = date.today()
        context["num_task_actual"] = Task.objects.filter(
            is_completed=True
        ).count()

        context["today"] = date.today()
        deadline = None

        for task in context["tasks_view_list"]:
            prefix = "days"
            deadline_date = (task.deadline - today).days
            if deadline_date == 1:
                prefix = "day"
            deadline = f"{deadline_date} {prefix} left"
            if not deadline_date:
                deadline = "Today is deadline"
            task.days_left = deadline

        return context


@method_decorator(require_POST, name="dispatch")
class TaskStatusUpdateView(generic.View):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_completed = not task.is_completed
        task.save()
        return JsonResponse({"is_completed": task.is_completed})


class TaskDetailView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "catalog/task_detail.html"
    success_url = reverse_lazy("catalog:task_url_list")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "catalog/task_create.html"
    success_url = reverse_lazy("catalog:task_url_list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("catalog:task_url_list")


class ProfileView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = ProfileForm
    template_name = "catalog/profile.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = date.today()
        task = Task.objects.filter(assignees=self.request.user)
        actual_task = task.filter(is_completed=True).count()
        solved_task = task.filter(is_completed=False).count()
        context["today"] = today
        context["actual_task"] = actual_task
        context["solved_task"] = solved_task
        return context

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(request=self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        current_user = self.request.user
        if (
            form.instance.pk != current_user.pk
            and not current_user.is_superuser
        ):
            return HttpResponseForbidden(
                "You are not allowed to edit this profile."
            )
        return super().form_valid(form)


def page_not_found(request, exception):
    return render(request, "http_response/page-404.html", status=404)


def permission_denied(request, exception):
    return render(request, "http_response/page-403.html", status=403)


def server_error(request):
    try:
        if "google-oauth2" in request.backend.name:
            with transaction.atomic():
                old_code = request.GET.get("verification_code")
                user = Code.objects.get(code=old_code, verified=False)
                email = user.email
                worker = Worker.objects.get(email=email)
                worker.waiting_verified = False
                worker.save()
                user.delete()
            return render(request, "http_response/google-500.html", status=500)
    except (AuthMissingParameter, AttributeError, Code.DoesNotExist) as e:
        return render(request, "http_response/page-500.html", status=500)

templates/catalog/index.html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/logo-6-1.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/logo-6-1.png">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

  <title>
    Task Manager - Home
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/material-kit.css?v=3.0.0" rel="stylesheet" />

</head>
<body class="presentation-page bg-gray-200">

  {% include 'includes/navigation.html' %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative animate__animated animate__fadeIn" style="background-image: url('{{ ASSETS_ROOT }}/img/bg_abstract.jpeg')">
      <span class="mask bg-gradient-dark opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto animate__animated animate__delay-1s animate__fadeIn">
            <h1 class="text-white pt-3 mt-n5">It`s private Task manager </h1>
            <p class="lead text-white mt-3">Free & Open Source Task manager <br /> </p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center shadow-primary rounded-3 ">
                  <h1 class="rounded-2 text-gradient text-dark"><span id="state1" countTo={{ num_task }}>0</span></h1>
                <h5 class="mt-3">Tasks</h5>
                  <p class="text-sm font-weight-normal">Number of all tasks ever set</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center shadow-primary rounded-3 ">
                  <h1 class="rounded-2 text-gradient text-dark"> <span id="state2" countTo={{num_task_actual}}>0</span></h1>
                <h5 class="mt-3">Actual tasks</h5>
                  <p class="text-sm font-weight-normal">Number of all actual tasks</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center shadow-primary rounded-3 ">
                  <h1 class="rounded-bottom text-gradient text-dark" id="state3" countTo={{ num_task_solved }}>0</h1>
                <h5 class="mt-3">Solved tasks</h5>
                  <p class="text-sm font-weight-normal">Number of all solved tasks</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <footer>
    {% include 'includes/footer.html' %}
  </footer>

  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>
</body>
</html>

templates/catalog/task_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %} {{ task.name }} {% endblock %}

{% block body_class %} index-page {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
  <style>
    .form-control {
      mask: 1px;
      box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
      border-radius: 10px;
      padding: 8px;
    }


  </style>
{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <div class="page-header min-vh-80 animate__animated animate__fadeIn" style="background-image: url('{{ ASSETS_ROOT }}/img/bg_coding.jpeg')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white animate__animated animate__delay-1s animate__fadeIn ">Task name: {{ object.name }}</h1>
            <h3 class="text-white animate__animated animate__delay-1s animate__fadeIn">Deadline is: {{ object.deadline }}</h3>
            {% if object.is_completed %}
              <h3 class="text-white animate__animated animate__delay-1s animate__fadeIn">Status: "Open"</h3>
            {% else %}
              <h3 class="text-white animate__animated animate__delay-1s animate__fadeIn">Status: "Closed"</h3>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl  mx-3 mx-md-4 mt-n6" style="min-width: 400px;">
    <div class="container">
      <div class="section text-center">
        <div class="container animate__animated animate__backInUp" style="max-width: 55%; min-width: 18em;">
          <form class="rounded-3 mx-auto m-lg-1" role="form" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{% url 'catalog:task_url_delete' task.pk %}" type="button" class="btn bg-gradient-primary">Delete</a>

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/catalog/task_list.html
{% extends "layouts/base.html" %}

{% block title %} Tasks {% endblock %}

{% block body_class %} index-page {% endblock %}

<!-- Specific Page CSS goes HERE  -->TaskListView
{% block stylesheets %}


{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}
  <div class="page-header min-vh-80 animate__animated animate__fadeIn" style="background-image: url('{{ ASSETS_ROOT }}/img/bg_pc.png')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white animate__animated animate__delay-1s animate__fadeIn ">All Active Tasks: {{ num_task_actual }}</h1>
            <h3 class="text-white animate__animated animate__delay-1s animate__fadeIn ">Today is: {{ today }}</h3>
            <a href="{% url 'catalog:task_url_create' %}" type="button" class=" animate__animated animate__delay-1s animate__fadeIn btn btn-lg btn-outline-secondary bg-gradient-success">Create new Task</a>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="mt-5 mt-md-5 album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for task in tasks_view_list %}
        <div class="col  animate__animated animate__backInLeft">
          <div class="card shadow-primary">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="175" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
              <a href="{% url 'catalog:task_url_detail' task.pk %}">
              <rect width="100%" height="100%" fill="#55595c"></rect>
              <text x="50%" y="50%" fill="#eceeef" dy=".3em" text-anchor="middle">
                Task-name: {{ task.name }}
                </text>
              </a>
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>Assignees</th>
                      <th>Position</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for assign in task.assignees.all %}
                    <tr>
                      <td text-anchor="middle" ><a href="{% url 'catalog:profile_url_detail' assign.pk %}">{{ assign.username }}</a></td>
                      <td>{{ assign.position }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </svg>
            <div class="card-body">
              <p class="card-text">Description: {{ task.description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary delete-task-btn task-status-btn {% if task.is_completed %}bg-gradient-success{% else %}bg-gradient-warning{% endif %}" data-task-id="{{ task.pk }}" data-is-completed="{{ task.is_completed }}">
                      {{ task.is_completed|yesno:"Done,Reopen" }}
                  </button>
                  <a href="{% url 'catalog:task_url_detail' task.pk %}" type="button" class="btn btn-sm btn-secondary">Edit</a>
                  <a href="{% url 'catalog:task_url_delete' task.pk %}" type="button" class="btn btn-sm bg-gradient-primary">Delete</a>
                </div>
                  {% if task.priority == '!!!' %}
                    <small class="text-body-secondary">
                      <h4 class="text-danger">{{ task.priority }}</h4>
                    </small>
                  {% elif task.priority == '!!' %}
                    <small class="text-body-secondary">
                      <h4 class="text-warning">{{ task.priority }}</h4>
                    </small>
                  {% elif task.priority == '!' %}
                    <small class="text-body-secondary">
                      <h4 class="text-success">{{ task.priority }}</h4>
                    </small>
                  {% endif %}
                  {% if task.is_completed %}
                  <small class="text-body-secondary">{{ task.days_left }}</small>
                  {% else %}
                  <small class="text-body-secondary">task closed</small>
                  {% endif %}

              </div>
            </div>
          </div>
        </div>
        {% empty %}
          <h1 class="">No tasks found</h1>
        {% endfor %}
      </div>
    </div>
  </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
  $(document).ready(function() {
      // Обработчик кликов на кнопках "Done"
      $('.task-status-btn').on('click', function(event) {
          event.preventDefault();
          var button = $(this);
          var taskId = button.data('task-id');
          var isCompleted = button.data('is-completed');
          $.ajax({
              url: '/task/' + taskId + '/update_status/',
              type: 'POST',
              data: {
                  csrfmiddlewaretoken: '{{ csrf_token }}',
                  is_completed: !isCompleted
              },
              dataType: 'json',
              success: function(data) {
                  button.data('is-completed', data.is_completed);
                  button.text(data.is_completed ? 'Done' : 'Reopen');
                  if (data.is_completed) {
                      button.removeClass('bg-gradient-warning').addClass('bg-gradient-success');
                  } else {
                      button.removeClass('bg-gradient-success').addClass('bg-gradient-warning');
                  }
                },
              error: function(xhr, textStatus, errorThrown) {
                  console.error(textStatus, errorThrown);
              }
          });
      });
  });
</script>



{% endblock javascripts %}